CAPTURE = 'capture'
FORWARD = 'forward'
BACKWARD = 'backward'
DOUBLE_MOVE = 'double move'
LONG_CASTLE = 'long castle'
SHORT_CASTLE = 'short castle'

KING = 'K'
QUEEN = 'q'
KNIGHT = 'k'
BISHOP = 'b'
ROOK = 'r'
PAWN = 'p'

BLACK: str = 'b'
WHITE: str = 'w'